/**
 * Uploading a picture.
 *
 * The only binary the product sends anywhere, and the only request in the
 * application that is not JSON — so it does not go through `apiRequest`, which
 * sets a `Content-Type` a multipart body must not have. (Setting
 * `multipart/form-data` by hand is the classic version of this bug: the
 * boundary is generated by `fetch` when it serialises a `FormData`, and a
 * hand-written header omits it, so the server sees a body it cannot parse.)
 *
 * ```text
 *   File ─→ POST /media/uploads ─→ { url: "/uploads/memory/2026/08/<id>.png" }
 *                                        ↓
 *                          stored in Memory.imageUrl, never the bytes
 * ```
 */

import { ApiError } from '../../lib/api';

const BASE_URL: string = import.meta.env.VITE_API_URL ?? 'http://localhost:3000';

export interface UploadedImage {
  fileId: string;
  /** The path to store and to render from. Relative to the API origin. */
  url: string;
  mimeType: string;
  sizeBytes: number;
  createdAt: string;
}

/** What the browser is allowed to offer in the file picker. */
export const ACCEPTED_IMAGE_TYPES = 'image/png,image/jpeg,image/webp';

/** Matches the server's cap, so an oversized file is refused before it is sent. */
export const MAX_IMAGE_BYTES = 5 * 1024 * 1024;

/**
 * An uploaded path turned into something an `<img>` can load.
 *
 * The API and the application are different origins in development, and the
 * stored path is deliberately origin-less — it is a location on the media
 * server, and baking a hostname into a database column is how a product ends up
 * unable to move house.
 */
export function imageSrc(url: string): string {
  return url.startsWith('http') ? url : `${BASE_URL}${url}`;
}

export async function uploadImage(
  file: File,
  signal?: AbortSignal,
): Promise<UploadedImage> {
  if (file.size > MAX_IMAGE_BYTES) {
    throw new ApiError(413, 'PAYLOAD_TOO_LARGE', 'Pictures have to be under 5 MB.');
  }

  const form = new FormData();
  form.append('file', file);
  form.append('purpose', 'memory');

  const response = await fetch(`${BASE_URL}/api/v1/media/uploads`, {
    method: 'POST',
    credentials: 'include',
    body: form,
    signal,
  });

  if (!response.ok) {
    const body = (await response.json().catch(() => null)) as {
      error?: { code: string; message: string };
    } | null;

    throw new ApiError(
      response.status,
      body?.error?.code ?? 'UNKNOWN',
      body?.error?.message ?? 'That picture could not be uploaded.',
    );
  }

  return (await response.json()) as UploadedImage;
}
